name: Run Parser Daily

# Controls when the action will run
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

  # Allows the workflow to be run manually (optional)
  workflow_dispatch:

# Job to run the script
jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: List installed packages
      run: pip list  # Verify installed packages
    # Step 4: Run the parser script
    - name: Run parser.py
      run: |
        python app/parser.py
